import "../styles/important.scss";
import style from "@/styles/App.module.scss";

export const metadata = {
  title: "Hassaam Mughal",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={style.body}>{children}</body>
    </html>
  );
}
